version: "3"
services:
  node-app:
    build: . 
    ports: 
      - "4000:4000"
    volumes: 
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.node-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    env_file:
      - ./.env.mongo
    volumes: 
      - mongo-db:/data/db

volumes:
  mongo-db: