version: "3"
services:
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.node-app
    command:
      npm run dev
    depends_on:
      - mongo
  mongo:
    env_file:
      - ./.env.mongo
    volumes:
      - mongo-db:/data/db